Use integral values for file sizes
AnthonyMDev/AmazonS3RequestManager pull request #65
Opened 2017-10-01 12:14 UTC by fpillet

Float conversions were producing errors. In several cases, converting the byte size from text to float produced a value that was off-by-one.

2017-10-02 19:51 UTC, AnthonyMDev requested changes

2017-10-02 19:51 UTC, AnthonyMDev commented on Source/ResponseObjects.swift
> +		print("sizeString='\(sizeString)' size=\(size) path=\(path)")
Please remove unneeded logging from the PR and I'd be happy to accept it. Thank you!

2017-10-02 21:19 UTC, fpillet commented on Source/ResponseObjects.swift
> +		print("sizeString='\(sizeString)' size=\(size) path=\(path)")
Removal is in the second commit (had realized I had left this one in just after pushing the PR). Let me know if you prefer me cancelling the PR and send out a clean one.

2017-10-12 17:39 UTC, merged

2017-10-12 17:39 UTC, AnthonyMDev commented
Thanks for this!